openapi: 3.0.0
info:
  contact:
    email: dev@tricoro.tech
    name: tricoro
    url: https://tricoro.tech/
  title: GMO Coin APIs
  version: 1.0.0
servers:
- url: https://api.coin.z.com
tags:
- description: Public APIs
  name: public
- description: Private APIs
  name: private
paths:
  /public/v1/status:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: OK
      summary: Get an exchange status
      tags:
      - public
  /public/v1/ticker:
    get:
      parameters:
      - explode: true
        in: query
        name: symbol
        required: false
        schema:
          $ref: '#/components/schemas/Symbols'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tickers'
          description: OK
      summary: Get latest rate
      tags:
      - public
  /public/v1/orderbooks:
    get:
      parameters:
      - explode: true
        in: query
        name: symbol
        required: true
        schema:
          $ref: '#/components/schemas/Symbols'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orderbooks'
          description: OK
      summary: Get orderbooks
      tags:
      - public
  /public/v1/trades:
    get:
      parameters:
      - explode: true
        in: query
        name: symbol
        required: true
        schema:
          $ref: '#/components/schemas/Symbols'
        style: form
      - description: page number. (default 1)
        explode: true
        in: query
        name: page
        required: false
        schema:
          type: integer
        style: form
      - description: Max count per request. (default 100)
        explode: true
        in: query
        name: count
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trades'
          description: OK
      summary: Get trade histories
      tags:
      - public
  /private/v1/account/margin:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountMargin'
          description: OK
      security:
      - ApiKey: []
        ApiTimestamp: []
        ApiSign: []
      summary: Get account margin
      tags:
      - private
  /private/v1/account/assets:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Assets'
          description: OK
      security:
      - ApiKey: []
        ApiTimestamp: []
        ApiSign: []
      summary: Get account assets
      tags:
      - private
  /private/v1/account/tradingVolume:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradingVolume'
          description: OK
      security:
      - ApiKey: []
        ApiTimestamp: []
        ApiSign: []
      summary: Get trading volume
      tags:
      - private
  /private/v1/order:
    post:
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                symbol:
                  $ref: '#/components/schemas/Symbols'
                side:
                  enum:
                  - BUY
                  - SELL
                  type: string
                executionType:
                  enum:
                  - MARKET
                  - LIMIT
                  - STOP
                  type: string
                timeInForce:
                  enum:
                  - FAK
                  - FOK
                  type: string
                price:
                  type: string
                losscutPrice:
                  type: string
                size:
                  type: string
                cancelBefore:
                  type: boolean
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: OK
      security:
      - ApiKey: []
        ApiTimestamp: []
        ApiSign: []
      summary: Order
      tags:
      - private
components:
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    StatusCode:
      description: 0 Nomal end
      type: integer
    Symbols:
      description: Crypted currency symbols
      enum:
      - BTC
      - ETH
      - BCH
      - LTC
      - XRP
      - XEM
      - XLM
      - XYM
      type: string
    Status:
      example:
        data: '{}'
        responsetime: 2000-01-23T04:56:07.000+00:00
        status: 0
      properties:
        status:
          description: 0 Nomal end
          type: integer
        data:
          properties:
            status:
              enum:
              - OPEN
              - MAINTENANCE
              - PREOPEN
              type: string
          required:
          - status
        responsetime:
          format: date-time
          type: string
      required:
      - data
      - responsetime
      - status
      type: object
    Tickers:
      example:
        data:
        - volume: 7.061401241503109
          symbol: symbol
          high: 5
          last: 5
          low: 2
          ask: 6
          bid: 1
          timestamp: 2000-01-23T04:56:07.000+00:00
        - volume: 7.061401241503109
          symbol: symbol
          high: 5
          last: 5
          low: 2
          ask: 6
          bid: 1
          timestamp: 2000-01-23T04:56:07.000+00:00
        responsetime: 2000-01-23T04:56:07.000+00:00
        status: 0
      properties:
        status:
          description: 0 Nomal end
          type: integer
        data:
          items:
            $ref: '#/components/schemas/Tickers_data'
          type: array
        responsetime:
          format: date-time
          type: string
      type: object
    Orderbooks:
      example:
        data:
          symbol: symbol
          asks:
          - size: 1
            price: 6
          - size: 1
            price: 6
          bids:
          - size: 1
            price: 6
          - size: 1
            price: 6
        responsetime: 2000-01-23T04:56:07.000+00:00
        status: 0
      properties:
        status:
          description: 0 Nomal end
          type: integer
        data:
          $ref: '#/components/schemas/Orderbooks_data'
        responsetime:
          format: date-time
          type: string
      type: object
    AccountMargin:
      example:
        data:
          margin: margin
          availableAmount: availableAmount
          marginRatio: marginRatio
          marginCallStatus: marginCallStatus
          profitLoss: profitLoss
          actualProfitLoss: actualProfitLoss
        responsetime: 2000-01-23T04:56:07.000+00:00
        status: 0
      properties:
        status:
          description: 0 Nomal end
          type: integer
        data:
          $ref: '#/components/schemas/AccountMargin_data'
        responsetime:
          format: date-time
          type: string
      type: object
    Trades:
      example:
        data:
          pagination:
            count: 1
            currentPage: 6
          list:
          - side: side
            size: size
            price: 5
            timestamp: 2000-01-23T04:56:07.000+00:00
          - side: side
            size: size
            price: 5
            timestamp: 2000-01-23T04:56:07.000+00:00
        responsetime: 2000-01-23T04:56:07.000+00:00
        status: 0
      properties:
        status:
          description: 0 Nomal end
          type: integer
        data:
          $ref: '#/components/schemas/Trades_data'
        responsetime:
          format: date-time
          type: string
      type: object
    Assets:
      example:
        data:
        - symbol: symbol
          amount: amount
          available: available
          conversionRate: conversionRate
        - symbol: symbol
          amount: amount
          available: available
          conversionRate: conversionRate
        responsetime: 2000-01-23T04:56:07.000+00:00
        status: 0
      properties:
        status:
          description: 0 Nomal end
          type: integer
        data:
          items:
            $ref: '#/components/schemas/Assets_data'
          type: array
        responsetime:
          format: date-time
          type: string
      type: object
    TradingVolume:
      example:
        data: '{}'
        responsetime: 2000-01-23T04:56:07.000+00:00
        status: 0
      properties:
        status:
          description: 0 Nomal end
          type: integer
        data:
          properties:
            jpyVolume:
              type: string
            tierLevel:
              type: string
            limit:
              items:
                properties:
                  symbol:
                    $ref: '#/components/schemas/Symbols'
                  todayLimitOpenSize:
                    type: string
                required:
                - symbol
                - todayLimitOpenSize
                type: object
              type: array
          required:
          - jpyVolume
          - limit
          - tierLevel
        responsetime:
          format: date-time
          type: string
      required:
      - data
      - responsetime
      - status
      type: object
    inline_object:
      properties:
        symbol:
          $ref: '#/components/schemas/Symbols'
        side:
          enum:
          - BUY
          - SELL
          type: string
        executionType:
          enum:
          - MARKET
          - LIMIT
          - STOP
          type: string
        timeInForce:
          enum:
          - FAK
          - FOK
          type: string
        price:
          type: string
        losscutPrice:
          type: string
        size:
          type: string
        cancelBefore:
          type: boolean
      type: object
    inline_response_200:
      example:
        data: data
        responsetime: 2000-01-23T04:56:07.000+00:00
        status: 0
      properties:
        status:
          description: 0 Nomal end
          type: integer
        data:
          description: orderid
          type: string
        responsetime:
          format: date-time
          type: string
      type: object
    Tickers_data:
      example:
        volume: 7.061401241503109
        symbol: symbol
        high: 5
        last: 5
        low: 2
        ask: 6
        bid: 1
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        ask:
          type: integer
        bid:
          type: integer
        high:
          type: integer
        last:
          type: integer
        low:
          type: integer
        symbol:
          $ref: '#/components/schemas/Symbols'
        timestamp:
          format: date-time
          type: string
        volume:
          format: double
          type: number
      type: object
    Orderbooks_data_asks:
      example:
        size: 1
        price: 6
      properties:
        price:
          type: integer
        size:
          type: integer
      type: object
    Orderbooks_data:
      example:
        symbol: symbol
        asks:
        - size: 1
          price: 6
        - size: 1
          price: 6
        bids:
        - size: 1
          price: 6
        - size: 1
          price: 6
      properties:
        asks:
          items:
            $ref: '#/components/schemas/Orderbooks_data_asks'
          type: array
        bids:
          items:
            $ref: '#/components/schemas/Orderbooks_data_asks'
          type: array
        symbol:
          $ref: '#/components/schemas/Symbols'
      type: object
    AccountMargin_data:
      example:
        margin: margin
        availableAmount: availableAmount
        marginRatio: marginRatio
        marginCallStatus: marginCallStatus
        profitLoss: profitLoss
        actualProfitLoss: actualProfitLoss
      properties:
        actualProfitLoss:
          type: string
        availableAmount:
          type: string
        margin:
          type: string
        marginCallStatus:
          type: string
        marginRatio:
          type: string
        profitLoss:
          type: string
      type: object
    Trades_data_pagination:
      example:
        count: 1
        currentPage: 6
      properties:
        currentPage:
          type: integer
        count:
          type: integer
      type: object
    Trades_data_list:
      example:
        side: side
        size: size
        price: 5
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        price:
          type: integer
        side:
          type: string
        size:
          type: string
        timestamp:
          format: date-time
          type: string
      type: object
    Trades_data:
      example:
        pagination:
          count: 1
          currentPage: 6
        list:
        - side: side
          size: size
          price: 5
          timestamp: 2000-01-23T04:56:07.000+00:00
        - side: side
          size: size
          price: 5
          timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        pagination:
          $ref: '#/components/schemas/Trades_data_pagination'
        list:
          items:
            $ref: '#/components/schemas/Trades_data_list'
          type: array
      type: object
    Assets_data:
      example:
        symbol: symbol
        amount: amount
        available: available
        conversionRate: conversionRate
      properties:
        amount:
          type: string
        available:
          type: string
        conversionRate:
          type: string
        symbol:
          $ref: '#/components/schemas/Symbols'
      type: object
  securitySchemes:
    ApiKey:
      in: header
      name: API-KEY
      type: apiKey
    ApiTimestamp:
      in: header
      name: API-TIMESTAMP
      type: apiKey
    ApiSign:
      in: header
      name: API-SIGN
      type: apiKey
